# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
  build2:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Send Email With AWS SES
        run: |
          aws ses send-email \
          --from "mincoding@naver.com" \
          --destination "ToAddresses=sejin.choi@mincoding.co.kr" \
          --message 'Subject={Data="안녕하십니까, 박지훈이라고 합니다.",Charset=UTF-8},Body={Html={Data="<div style=font-family:sans-serif;line-height:1.7><h2 style=color:#C33A2E;margin:0>🐉 박지훈 열전</h2><p><b>10년 내로 삼성SDS의 임원이   될 남자 박지훈 인사드립니다.</b></p><p>2002년생, 지난주 금요일 AI Advanced <b>100점</b>으로 정복. 이러한 이유로 AI Expert 또한 제   손아귀에 들어올 수밖에 없는 운명이며, SW Expert는 올해 안에 1트로 제 것이 될 예정입니다.</p><p>취미는 바둑, 운동은 탁구, 음식은 제육 <b>두 그릇</b>. 10년 뒤엔 최초의 CL2 출신 금융실행전략그룹 그룹장.</p><p style=color:#6b7280><i>이것은 자랑이 아니라, 그냥 사실을 미리 알려드리는 서비스인 것.</i></p><p>동료 여러분, 지금 저를 바라보며 무언가를 느끼고 계실 것으로 사료됩니다. 많은 사랑과 관심 부탁드립니다.</p><a href=https://sds-junior-reviewer-2026-second.github.io/ptest-Jihun/>🐉 박지훈 열전 보러가기</a></div>",Charset=UTF-8}}'
